project:
  type: website

website:
  title: "biostat777-intro-meklityimenu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    fontsize: 1.1em
    css: styles.css
    toc: true

editor: visual

