project:
  type: website

website:
  title: "Meklit Yimenu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    fontsize: 1.6em
    mainfont: serif
    headfont: serif
    linestretch: 1.7
    css: styles.css
    toc: true

editor: visual

